### ISSUE TITLE
GapFillFailedException on Resend From a Date

### ISSUE THREAD

**Issue by sajjadkarimi** [streamr-dev/streamr-client-java#59]
Recently, I have written a code using streamr-client-java to get historical data by ResendFromOption configuration.
you can see a part of my code below:

` StreamrClientOptions options = new StreamrClientOptions(new EthereumAuthenticationMethod(apiKey));`
` options.setSkipGapsOnFullQueue(false);`
` StreamrClient client = new StreamrClient(options);`
` ResendFromOption fromOption = new ResendFromOption(fromDate);`
` try {`
`        Stream stream = client.getStream(streamId);`
`        client.subscribe(stream, 0, new MessageHandler() {`
`              @Override`
`               public void onMessage(Subscription s, StreamMessage streamMessage) {`

In addition, ```fromDate``` is date of about 1 month ago and also ```streamId``` is KT1OgUisRZq_DOEoKz3Q9Q.

After execution, I have realized that this exception has happened:

`20/10/12 21:23:43 WARN OrderedMsgChain: Unable to fill gap: Max retries reached! Ignoring the error and continuing from the` `first processable message: 1599162495509-0` 
`Exception in thread "Timer-2" com.streamr.client.exceptions.GapFillFailedException: Failed to fill gap between` `1599162335079-1 and 1599162475499-0 for 0x11193c28c4f638dd6c9a7f68684d74ab93b60531-f3bnN2jetvUK2mcngNdc after` `10 trials`
`	at com.streamr.client.utils.OrderedMsgChain$2.run(OrderedMsgChain.java:209)`
`	at java.util.TimerThread.mainLoop(Timer.java:555)`
`	at java.util.TimerThread.run(Timer.java:505)`

It seems that this problem would result in data loss, as it commented in OrderedMsgChain.java:
                           
`// Currently unrecoverable gaps are just ignored, and processing continues from the next`
`// message after the gap.`

Would you please describe the root cause of this exception? And if there is a bug, we can fix it together.

**Comment by hpihkala** [comment]
The root cause for the warning is that some historical messages that _should_ exist could not be retrieved from storage. The client knows about their existence because the messages are chained: a message refers to the previous message, allowing for gap detection and perfect ordering of messages.

This could occur for example if the storage facility fails to store some messages, or if the client creates messages but fails to publish them. It's not usually a fatal problem, but depends on the use case. In some cases missing data points could be a severe problem, while in some, it can just be ignored. The client prints a warning (which you copied here), but should continue operations normally.

So the expected behavior in the client library is that it detects this situation, prints the warning, and then ignores the gap and continues from the next message after the gap. There's some test coverage for this, so at least simple cases should work as expected, but we can try to replicate with a real-world stream such as yours.

If the client library seems to work as intended, but the resend is still getting cut off abruptly, then it's probably a network-level problem where connections to the storage node(s) might get closed prematurely, or the volume of data being sent prevents heartbeats from going through, and the connections get closed for that reason.

If it's a network problem and not a client problem, then one workaround could be to try and do smaller resends, for example do one day or just one hour at a time:

```
while (fromDate < endDate) {
    ResendOption option = new ResendRangeOption(fromDate, toDate);
    client.resend(..., option);
    // wait until the done method in the message handler is called
    // update fromDate and toDate by moving them forward to cover the next timespan
}
```

**Comment by hpihkala** [comment]
Hi, we discovered some issues with prematurely terminating resends on the Streamr Network level, and we are working on fixing them now. It makes sense to debug the client only when the network level works flawlessly - otherwise it will be hard to tell which behavior is caused by the network and which is caused by the client.

So it will take some time to get all of that sorted, but we're making some progress. Part of the prematurely terminating resend issue has already been fixed. You should now get quite reliable resends if you configure the client to connect directly to the storage node. (Otherwise the resends are proxied via the node you connect to, and this is currently still buggy). There is currently only one storage node in the network and the address of its websocket interface is `wss://corea1.streamr.network:7001/api/v1/ws`, which you can pass as the `websocketApiUrl` to the `StreamrClientOptions` object.

> It seems that StreamrClient.this.unsubscribe(sub) dose not remove Subscription from subsByStreamIdAndPartition when done method of message handler calls.

Ah, could be! Would you like to help by writing a test that reproduces the problem and fixing it? We'd be happy to receive a pull request. Otherwise we'll take a look as soon as the resends are working reliably on the network level. 

In any case you could now try the "long" resends again (using the `websocketApiUrl` above) instead of the piece-by-piece approach. Note that you'll still see the warnings about missing messages (that's correct behavior of the client), but you should get a lot more messages than before, instead of the resend just abruptly stopping. At least with the CLI tool / JS client this now works when connected directly to the storage node, so there's a chance that it works on the Java client too.

```
streamr resend range "2020-10-01" "2020-10-15" KT1OgUisRZq_DOEoKz3Q9Q --private-key <PRIVATE-KEY> --ws-url=wss://corea1.streamr.network:7001/api/v1/ws --disable-ordering | wc
```

The above command using the CLI client now seems to quite reliably return `491415` messages (as counted using `wc`), this is a good first step.

CC @harbu who is working on the network resends currently.

**Comment by sajjadkarimi** [comment]
Hi, this is my code as you said:

`StreamrClientOptions options = new StreamrClientOptions(new EthereumAuthenticationMethod(apiKey));`
`options.setSkipGapsOnFullQueue(false);`
`options.setWebsocketApiUrl("wss://corea1.streamr.network:7001/api/v1/ws");
`StreamrClient client = new StreamrClient(options);`

and I saw this exception again:

`Exception in thread "Timer-2" com.streamr.client.exceptions.GapFillFailedException: Failed to fill gap between` `1599162335079-1 and 1599162475499-0 for 0x11193c28c4f638dd6c9a7f68684d74ab93b60531-f3bnN2jetvUK2mcngNdc` `after 10 trials`
`	at com.streamr.client.utils.OrderedMsgChain$2.run(OrderedMsgChain.java:209)`
`	at java.util.TimerThread.mainLoop(Timer.java:555)`
`	at java.util.TimerThread.run(Timer.java:505)`
`08:59:21.969 WARN [c.s.c.u.OrderedMsgChain]  Unable to fill gap: Max retries reached! Ignoring the error and continuing` `from the first processable message: 1599162495509-0`

and also I'll work on unsubscribing problem on this weekend.

**Comment by sajjadkarimi** [comment]
It would be appreciated if you help me know that how can I run Integration Tests on my laptop? 

I've faced this problem after running tests:

`Resource not found: POST http://localhost/api/v1/login/challenge/0x69b9bda76aac29aa2029208b320d856b7124e241`
`com.streamr.client.exceptions.ResourceNotFoundException: Resource not found: POST http://localhost/api/v1/login/challenge`
`/0x69b9bda76aac29aa2029208b320d856b7124e241`
`	at com.streamr.client.utils.HttpUtils.assertSuccessful(HttpUtils.java:40)`
`	at com.streamr.client.authentication.AuthenticationMethod.post(AuthenticationMethod.java:50)`
`	at com.streamr.client.authentication.EthereumAuthenticationMethod.getChallenge(EthereumAuthenticationMethod.java:49)`
`	at com.streamr.client.authentication.EthereumAuthenticationMethod.login(EthereumAuthenticationMethod.java:32)`
`	at com.streamr.client.authentication.AuthenticationMethod.newSessionToken(AuthenticationMethod.java:27)`
`	at com.streamr.client.authentication.Session.getSessionToken(Session.java:25)`
`	at com.streamr.client.StreamrRESTClient.addAuthenticationHeader(StreamrRESTClient.java:56)`
`	at com.streamr.client.StreamrRESTClient.executeWithRetry(StreamrRESTClient.java:78)`
`	at com.streamr.client.StreamrRESTClient.post(StreamrRESTClient.java:104)`
`	at com.streamr.client.StreamrRESTClient.post(StreamrRESTClient.java:97)`
`	at com.streamr.client.StreamrRESTClient.createStream(StreamrRESTClient.java:146)`
`	at com.streamr.client.StreamrWebsocketSpec.setup(StreamrWebsocketSpec.groovy:32)`

**Comment by hpihkala** [comment]
Yeah those warnings are ok, they just mean that some messages failed to store and don't exist anymore. The client should ignore them and keep going. 

The important question is, is the resend giving you all the messages that _did_ get stored.

You can compare a resend using the Java client with a resend using the CLI tool. For example if you do a resend on your stream `KT1OgUisRZq_DOEoKz3Q9Q ` from `2020-10-01` (midnight UTC) to `2020-10-02` (also midnight UTC), you should get exactly `43418` messages with both methods.

```
streamr resend range "2020-10-01T00:00:00Z" "2020-10-02T00:00:00Z" KT1OgUisRZq_DOEoKz3Q9Q --private-key <private-key> --ws-url=wss://corea1.streamr.network:7001/api/v1/ws --disable-ordering | wc

# gives the wc output (43418 lines)
   43418 1141830 32617774
```

If you get the same number of messages with the Java client, then it seems to work well. If you get less messages, then I suspect there is still some problem with the client.

Thanks for your PR related to the repeated resends, much appreciated!
